// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGqv8Z8Sfwjx2ebvJQmvIc6nr4NaKn6M0',
    appId: '1:851241220515:web:d4ae739201ed2d5770c216',
    messagingSenderId: '851241220515',
    projectId: 'anicaretrack',
    authDomain: 'anicaretrack.firebaseapp.com',
    storageBucket: 'anicaretrack.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrDmcBzSD0SelQHfBlddln8Bdun9ovPEk',
    appId: '1:851241220515:android:8374c765af64755470c216',
    messagingSenderId: '851241220515',
    projectId: 'anicaretrack',
    storageBucket: 'anicaretrack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWwXEizz_sm8DRSPKVhG_HkyJI1vhY6BY',
    appId: '1:851241220515:ios:a76401525169ab3f70c216',
    messagingSenderId: '851241220515',
    projectId: 'anicaretrack',
    storageBucket: 'anicaretrack.firebasestorage.app',
    iosBundleId: 'com.example.anicaretrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWwXEizz_sm8DRSPKVhG_HkyJI1vhY6BY',
    appId: '1:851241220515:ios:a76401525169ab3f70c216',
    messagingSenderId: '851241220515',
    projectId: 'anicaretrack',
    storageBucket: 'anicaretrack.firebasestorage.app',
    iosBundleId: 'com.example.anicaretrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGqv8Z8Sfwjx2ebvJQmvIc6nr4NaKn6M0',
    appId: '1:851241220515:web:9094b910781ecba270c216',
    messagingSenderId: '851241220515',
    projectId: 'anicaretrack',
    authDomain: 'anicaretrack.firebaseapp.com',
    storageBucket: 'anicaretrack.firebasestorage.app',
  );
}
